### ISSUE TITLE
Include Help text of Content Types

### ISSUE THREAD

**Issue by BarryNeu** [contentful/contentful-bootstrap.rb#37]
Improvement to the bootstrap utility. In a Content Type -> Settings (on a Field) -> Appearance. Help text is not included in the JSON extract and is therefore lost information in the imported space.

Using version
contentful_bootstrap v 3.1.1

**Comment by dlitvakb** [comment]
Hey Barry,

Thanks for creating the issue.

I've evaluated the changes required and this requires a new release on the CMA SDK that depends on the Editor Interface API, which is not currently ready for merge as we're about to do some refactor on the Public API that involves that specific endpoint.

Also, this change includes refactoring the bootstrap codebase to use the new 1.x release of the CMA SDK which is incompatible with the 0.x version this gem uses, it's not a big refactor, but it will take some time, enough time to require to formally add it to our next sprint.

One last thing, as the JSON exporter uses only Public data available through the CDA API, adding the help text on imports would require either manual intervention, or an extra script using the aforementioned Editor Interface API.

I'll address this as soon as the Editor Interface API is done and the CMA SDK merge is complete, you can follow progress on that issue [here](https://github.com/contentful/contentful-management.rb/pull/99)

Hope this helps,

Cheers

**Comment by dlitvakb** [comment]
This issue has been deprecated, as this gem is utilised for simple space templates. For a complete full import export flow, use the [Contentful CLI](https://github.com/contentful/contentful-cli).

Cheers
