### ISSUE TITLE
Avoid all puts and gets when in library use

### ISSUE THREAD

**Issue by benben** [contentful/contentful-bootstrap.rb#48]
Creating spaces in library mode still yields all puts and asks if the delivery token should be written to the conf file, which errors since there is no stdin

    Do you want to write the Delivery Token to your configuration file? (Y/n): Errno::ENOENT: No such file or directory @ rb_sysopen

**Comment by dlitvakb** [comment]
Hey @benben,

Would you be OK with passing an extra parameter in the options for the commands to detect this?

It's the only reliable way to determine if output is desired or not.

Also, this can be separated onto 2 distinct items:
1. `quiet` to silence output
2. `no_input` to remove user prompts

Does that sound good?

Cheers

**Comment by benben** [comment]
yes!

**Comment by dlitvakb** [comment]
For `quiet`, PR is already here! #49
