### ISSUE TITLE
Error importing entry with 'JSON Object' field type.

### ISSUE THREAD

**Issue by nghedia** [contentful/contentful-bootstrap.rb#51]
Hi, 

Seems there is an issue when trying to import an entry that has a 'JSON Object' field type in its content model. It appears that bootstrap is trying to 'create_link' and throws an error as 'linkType' is not defined.

**Content Type**
`
        {
          "id": "legacyPostImage",
          "name": "Legacy Post Image",
          "type": "Object"
        }
`

**Entry**

`
          "legacyPostImage": {
              "s": {
                  "w": 160,
                  "h": 160,
                  "url": "xxxxx"
              }
`

**Error**

`/Library/Ruby/Gems/2.0.0/gems/contentful_bootstrap-3.4.0/lib/contentful/bootstrap/templates/json_template.rb:158:in `create_link': undefined method `capitalize' for nil:NilClass (NoMethodError)
	from /Library/Ruby/Gems/2.0.0/gems/contentful_bootstrap-3.4.0/lib/contentful/bootstrap/templates/json_template.rb:139:in `block (3 levels) in process_entries'
	from /Library/Ruby/Gems/2.0.0/gems/contentful_bootstrap-3.4.0/lib/contentful/bootstrap/templates/json_template.rb:138:in `each'
	from /Library/Ruby/Gems/2.0.0/gems/contentful_bootstrap-3.4.0/lib/contentful/bootstrap/templates/json_template.rb:138:in `block (2 levels) in process_entries'
	from /Library/Ruby/Gems/2.0.0/gems/contentful_bootstrap-3.4.0/lib/contentful/bootstrap/templates/json_template.rb:122:in `each'
	from /Library/Ruby/Gems/2.0.0/gems/contentful_bootstrap-3.4.0/lib/contentful/bootstrap/templates/json_template.rb:122:in `block in process_entries'
	from /Library/Ruby/Gems/2.0.0/gems/contentful_bootstrap-3.4.0/lib/contentful/bootstrap/templates/json_template.rb:113:in `each'
	from /Library/Ruby/Gems/2.0.0/gems/contentful_bootstrap-3.4.0/lib/contentful/bootstrap/templates/json_template.rb:113:in `process_entries'
	from /Library/Ruby/Gems/2.0.0/gems/contentful_bootstrap-3.4.0/lib/contentful/bootstrap/templates/json_template.rb:28:in `initialize'
	from /Library/Ruby/Gems/2.0.0/gems/contentful_bootstrap-3.4.0/lib/contentful/bootstrap/commands/update_space.rb:50:in `new'
	from /Library/Ruby/Gems/2.0.0/gems/contentful_bootstrap-3.4.0/lib/contentful/bootstrap/commands/update_space.rb:50:in `update_json_template'
	from /Library/Ruby/Gems/2.0.0/gems/contentful_bootstrap-3.4.0/lib/contentful/bootstrap/commands/update_space.rb:28:in `run'
	from /Library/Ruby/Gems/2.0.0/gems/contentful_bootstrap-3.4.0/lib/contentful/bootstrap/command_runner.rb:32:in `update_space'
	from /Library/Ruby/Gems/2.0.0/gems/contentful_bootstrap-3.4.0/bin/contentful_bootstrap:115:in `<top (required)>'
	from /usr/local/bin/contentful_bootstrap:22:in `load'
	from /usr/local/bin/contentful_bootstrap:22:in `<main>'
`

**Comment by dlitvakb** [comment]
Hey @nghedia,

This is currently a known issue and will be fixed when this gem gets upgraded to using the 1.x version of the Contentful Management SDK (it's not related to the upgrade, but this issue will be tackled at the same time).

It's currently planned to be done during this quarter, but no specific date yet. I'll try to bring it up during next planning so we can tackle this issue sooner.

I'll keep you up to date regarding this topic.

Feel free to submit yourself a patch if you want to have this resolved sooner, I'll review it ASAP.

Cheers

**Comment by dlitvakb** [comment]
Got approval to work on this right now,

I'm currently done with the SDK upgrades, and looking into the Object field issue right now.

Will create a PR and link it to this issue as soon as I'm done.

Cheers

**Comment by nghedia** [comment]
Amazing, thanks David! look forward to the fix.

**Comment by dlitvakb** [comment]
Hey @nghedia,

Fix is now under review, once it's merged, I'll create a new release.

Cheers

**Comment by dlitvakb** [comment]
This is now part of release `3.5.0` feel free to update your gem

Cheers
