### ISSUE TITLE
ISO date defaulting to 01-01-1970T01:33+01:00

### ISSUE THREAD

**Issue by nghedia** [contentful/contentful-bootstrap.rb#56]
Hi, so I'm experiencing an issue when updating a space with new entries.

I have a date field that I'm setting, and although the entry is created and published without any errors get the following...

<img width="536" alt="screen shot 2017-03-23 at 14 25 06" src="https://cloud.githubusercontent.com/assets/20408351/24252163/94f72bee-0fd4-11e7-832b-8a2a8f52b779.png">
The value I have in my JSON file is this...
`"startDate": "2017-03-16T22:00:12Z",`

Any ideas?

**Comment by dlitvakb** [comment]
Hey @nghedia,

Looks like a bug, I'll take into it as soon as possible.

Cheers

**Comment by nghedia** [comment]
@dlitvakb - thanks. Just an update.. if I import the same entry twice, the date updates correctly.

**Comment by dlitvakb** [comment]
Looks like it has to do with the tool creating first a shell entry and then updating it with the value, looks like in the case of Dates it's not updating properly.

I'll try looking into that early next week.

Cheers
