### ISSUE TITLE
Importing arrays doesn't work

### ISSUE THREAD

**Issue by Tribe216** [contentful/contentful-bootstrap.rb#69]
It looks like an issue similar to past issue #22 has cropped up.

Basically, when I export a space to JSON that contains a content type with an Array field, and then import that JSON into a new space, the expected Array field is a corrupted Object type instead of the expected Array.

To recreate:

Create a sample space from the included "Catalog" space.
`contentful_bootstrap create_space catalogue_1 --template=catalogue`

In Contentful:
  - Go to “Content Model” -> “Product”
  - Add field “Tags” of type “Text” and check “List”

Grab the space JSON and use it to create a new space:
`contentful_bootstrap generate_json <SPACE_ID> <DELIVERY_KEY> --output-file ./catalog.json`
`contentful_bootstrap create_space catalogue_2 --json-template ./catalog.json`

In Contentful:
  - Go to “Content Model” -> “Product”
  - Field “Tags” is an Object (Not list of Text’s).
  - Click on “Tags”. This should result in a "The application has encountered a problem and needs to reload.” dialog

Gem versions:
https://gist.github.com/Tribe216/f80be7955f67367232018a72ce75bc78

**Comment by Tribe216** [comment]
Gem versions:
https://gist.github.com/Tribe216/f80be7955f67367232018a72ce75bc78

**Comment by Tribe216** [comment]
figured it out .. uploading fix momentarily

**Comment by Tribe216** [comment]
https://github.com/contentful/contentful-bootstrap.rb/pull/70

**Comment by dlitvakb** [comment]
Merged, will make a release now
